### ISSUE TITLE
git tags should be annotated

### ISSUE THREAD

**Issue by veltzer** [noirbizarre/bumpr#15]
When bumpr issues "git tag [tagname]" (in vcs.py) it should create an annotated tag  (-a or --annotate).

Why?
- git best practice is for versions to be annotated tags.
- in some best practice configurations only annotated tags get pushed (see git followTags config).

So bumpr should only create annotated tags.

If backwards compatibility is an issue then at least an option to create annotated tags instead of the current behaviour to create lightweight tags should be added.

**Comment by noirbizarre** [comment]
I added a `tag_annotation` option in the `0.3.7` release.
Simply add to your bumpr.rc:
```ini
[bumpr]
tag_annotation = version {version}
```
And the tag will be annotated with the message `version X.Y.Z`
